# Generated by Django 4.2 on 2024-06-25 15:00

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=orders.models.generaste_code, max_length=8, verbose_name='Code'),
        ),
    ]
