# Generated by Django 4.2 on 2024-06-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
